/*
  sliderData is autogenerated to include all images in the `images/` folder
  except `avatar.jpg`. Each item has:
    - title: short readable label
    - img: path to the image
    - url: target page for the detail view (keeps existing simple-project.html)
*/
export const sliderData = [
    { title: "11B4655D", img: "images/11B4655D689DC7492B4165D440ECEFB7.jpg", url: "simple-project.html" },
    { title: "1EE3A6F4", img: "images/1EE3A6F4DEB87F93CD3B1680416D0C19.jpg", url: "simple-project.html" },
    { title: "46373565", img: "images/4637356589ED423FEA4BA6648AA21585.jpg", url: "simple-project.html" },
    { title: "5AF6CB4A", img: "images/5AF6CB4A41E426117DDBEE4AC5EF0246.jpg", url: "simple-project.html" },
    { title: "81FC8B03", img: "images/81FC8B034895014C25AAC08617BAF429.jpg", url: "simple-project.html" },
    { title: "92847E84", img: "images/92847E84FEA8F4BB48FB4279AB536812.jpg", url: "simple-project.html" },
    { title: "A34E65A0", img: "images/A34E65A036CC1939CFF55D81361744B0.jpg", url: "simple-project.html" },
    { title: "A4947810", img: "images/A4947810FE8E0856774E95F3D6F22103.jpg", url: "simple-project.html" },
    { title: "AA1EEA81", img: "images/AA1EEA810C38B283024A91D9095B74AB.jpg", url: "simple-project.html" },
    { title: "B6D5A391", img: "images/B6D5A3919F0110DCF8FEEA313E1162FF.jpg", url: "simple-project.html" },
    { title: "B9C6144F", img: "images/B9C6144F9672F0A7C08D1180984BF582.jpg", url: "simple-project.html" },
    { title: "C2B7EB5D", img: "images/C2B7EB5DB7443BD90347192228DBCB27.jpg", url: "simple-project.html" },
    { title: "84D75C82", img: "images/84D75C8229F65FBE38BFDD1448584FC0.jpg", url: "simple-project.html" },
    { title: "9E278E71", img: "images/9E278E71FA67CE52DFE59636285D8271.jpg", url: "simple-project.html" },
    { title: "CBE1BD37", img: "images/CBE1BD3707A363502E98D17DBE65948A.jpg", url: "simple-project.html" },
];
